### ISSUE TITLE
unused `default_get_install_dependencies` and not using the customization `get_install_dependencies`

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#305]
I couldn't find any references of `default_get_install_dependencies`:  https://github.com/search?q=repo%3Apython-wheel-build%2Ffromager%20default_get_install_dependencies&type=code (apart from the docs)

Similarly for the custom override `get_install_dependencies` I can't find any reference to it:  https://github.com/search?q=repo%3Apython-wheel-build%2Ffromager+get_install_dependencies&type=code

It seems like we are using `get_install_dependencies_of_wheel` over these 2 functions: https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L269

**Comment by dhellmann** [comment]
Those older functions were the old approach. Standardizing on building the wheel then getting the installation dependencies means we can get the dependencies from pre-built wheels, too. We also found that asking for the installation dependencies from the source tree was doing a large portion of the build work in order to produce the metadata that had the answer, so we might as well just build the wheel.

I think we can delete the old functions and override.
