### ISSUE TITLE
Remove `--wheel-server-url` arg for build-sequence command

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#423]
`--wheel-server-url` option is not applicable for the `build-sequence` command. We should probably remove it from main and define it only for the commands that need it

**Comment by dhellmann** [comment]
I think the confusion we've been having is that we're passing it to `bootstrap` when we shouldn't, and so wheels that haven't been built yet aren't available in the bootstrap environment. So I think we want to remove it from `bootstrap`.

For `build-sequence`, we want to take advantage of the wheels that might already be built and published to the index, so we want to keep the argument there. Otherwise we'll always build all wheels in the build-order file.

**Comment by shubhbapna** [comment]
Actually I think only place where we might need the `--wheel-server-url` is in the `step` commands

**Comment by dhellmann** [comment]
Downstream we run bootstrap without a wheel index argument so the built-in server is used. That ensures that we build everything we need and don't fail because something we build isn't available to pull from the wheel server. We make the job faster by copying files into the local server directory before we start.

Downstream when we run build-sequence, we want the opposite behavior. We build wheels and then push them one at a time to the server using a build hook. The build-sequence job is for making production wheels, and so it's safe to push them as we go. They are then available for building the next wheel, because we use the real package index as the cache instead of the local directory.

The step commands run all the same code and would want the same capability as build-sequence.

**Comment by shubhbapna** [comment]
Discussed offline: will be removing it from both build-sequence and bootstrap. Will add the cache url argument for build-sequence as well
